from typing import Protocol, Any


class DataStore(Protocol):
    def insert_one(self, collection: str, document: dict) -> Any: ...
    def insert_many(self, collection: str, documents: list[dict]) -> Any: ...
    def find_one(self, collection: str, query: dict) -> dict | None: ...
    def find_many(self, collection: str, query: dict, projection: dict | None = None) -> list[dict]: ...
    def count(self, collection: str) -> int: ...
    def update_one(self, collection: str, query: dict, document: dict) -> int: ...
