from typing import Protocol, Any, TypeVar

T = TypeVar("T")


class DataStore(Protocol[T]):
    def insert_one(self, table: str, object: T) -> Any: ...
    def insert_many(self, table: str, objects: list[T]) -> Any: ...
    def find_one(self, table: str, model_class: type[T], field: str, value: Any) -> T | None: ...
    def find_many(self, table: str, model_class: type[T], field: str | None = None, value: Any | None = None) -> list[T]: ...
    def count(self, table: str) -> int: ...
    def update_one(self, table: str, field: str, value: Any, object: T) -> int: ...

